# Generated by Django 6.0.4 on 2026-05-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ПІБ майстра')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('specialization', models.CharField(blank=True, max_length=100, verbose_name='Спеціалізація')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання')),
            ],
            options={
                'verbose_name': 'Майстер',
                'verbose_name_plural': 'Майстри',
                'ordering': ['full_name'],
            },
        ),
    ]
