# Generated by Django 5.2.7 on 2025-12-04 22:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100, verbose_name='Марка')),
                ('model_name', models.CharField(max_length=100, verbose_name='Модель')),
                ('vin', models.CharField(help_text='17 символів', max_length=17, unique=True, validators=[django.core.validators.MinLengthValidator(17)], verbose_name='VIN-код')),
                ('owner_name', models.CharField(help_text='ПІБ клієнта', max_length=100, verbose_name="Ім'я власника")),
                ('year', models.PositiveIntegerField(help_text='Використовуйте формат: <YYYY>', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)], verbose_name='Рік випуску')),
                ('color', models.CharField(max_length=50, verbose_name='Колір')),
                ('transmission', models.CharField(choices=[('manual', 'Механічна'), ('automatic', 'Автоматична'), ('robot', 'Роботизована'), ('variator', 'Варіатор')], default='automatic', max_length=20, verbose_name='Коробка передач')),
                ('fuel_type', models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('electric', 'Електро'), ('hybrid', 'Гібрид'), ('gas', 'Газ')], default='petrol', max_length=20, verbose_name='Тип пального')),
                ('mileage', models.PositiveIntegerField(default=0, help_text='Для нових авто залиште 0', verbose_name='Пробіг (км)')),
                ('engine_volume', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name="Об'єм двигуна (л)")),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='cars/%Y/%m/', verbose_name='Головне фото')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
            ],
            options={
                'verbose_name': 'Автомобіль',
                'verbose_name_plural': 'Автомобілі',
                'ordering': ['-created_at'],
            },
        ),
    ]
