# Generated by Django 6.0.4 on 2026-04-28 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='cars/%Y/%m/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='car',
            name='owner_name',
            field=models.CharField(max_length=100, verbose_name='ПІБ власника'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.MinLengthValidator(17)], verbose_name='VIN-код'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(help_text='Використовуйте формат: <YYYY>', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2027)], verbose_name='Рік випуску'),
        ),
    ]
