# Generated by Django 6.0.4 on 2026-04-28 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_main_image_alter_car_owner_name_and_more'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='clients.client', verbose_name='Власник'),
        ),
        migrations.AlterField(
            model_name='car',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='ПІБ власника'),
        ),
    ]
